const state={user:null,applications:[],teams:[],players:[],fixtures:[],results:[],venues:[]};
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const fmtDate=value=>value?new Date(value).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'—';
async function api(path,options={}){const response=await fetch(`/api/${path}`,{credentials:'same-origin',headers:{'content-type':'application/json',...(options.headers||{})},...options});const data=await response.json().catch(()=>({error:'Unexpected server response'}));if(!response.ok)throw new Error(data.error||'Request failed');return data}
function banner(message,type='ok'){const el=document.querySelector('#system-banner');el.innerHTML=`<strong>${type==='ok'?'Secure League Office':'Action needed'}</strong> ${escapeHtml(message)}`;el.style.background=type==='ok'?'#e1f0e9':'#fff3d6';el.style.color=type==='ok'?'#285f49':'#715813'}
function showView(name){document.querySelectorAll('.view').forEach(view=>view.classList.toggle('active',view.id===`${name}-view`));document.querySelectorAll('#admin-nav button').forEach(button=>button.classList.toggle('active',button.dataset.view===name));document.querySelector('.sidebar').classList.remove('open')}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.view)));
document.querySelectorAll('[data-view-jump]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.viewJump)));
document.querySelector('.mobile-menu').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));

function renderApplications(){const query=(document.querySelector('#application-search').value||'').toLowerCase();const filter=document.querySelector('#application-filter').value;const rows=state.applications.filter(item=>(filter==='All statuses'||item.status===filter)&&(!query||`${item.name} ${item.email} ${item.town} ${item.interest_type} ${item.team_name||''} ${item.venue_name||''}`.toLowerCase().includes(query)));document.querySelector('#applications-body').innerHTML=rows.map(item=>`<tr><td><strong>${escapeHtml(item.name)}</strong><br><small>${escapeHtml(item.email)}</small></td><td>${escapeHtml(item.interest_type)}${item.team_name?`<br><small>${escapeHtml(item.team_name)}</small>`:''}</td><td>${escapeHtml(item.town)}</td><td>${fmtDate(item.created_at)}</td><td><span class="status ${escapeHtml(item.status)}">${escapeHtml(item.status)}</span></td><td><select class="status-change" data-id="${item.id}"><option>New</option><option>Contacted</option><option>Approved</option><option>Declined</option></select>${item.interest_type==='Team'?` <button type="button" class="convert-application" data-application-details="${item.id}">View team</button>`:''}${item.converted_resource?` <span class="converted-label">Added to ${escapeHtml(item.converted_resource)}</span>`:item.status!=='Declined'?` <button type="button" class="convert-application" data-convert-application="${item.id}">Add to league</button>`:''}</td></tr>`).join('');document.querySelector('#applications-empty').classList.toggle('show',!rows.length);document.querySelectorAll('.status-change').forEach(select=>{const item=state.applications.find(row=>String(row.id)===select.dataset.id);select.value=item.status;select.addEventListener('change',async()=>{select.disabled=true;try{await api(`admin/applications/${item.id}`,{method:'PATCH',body:JSON.stringify({status:select.value})});await loadData();banner('Application status updated.')}catch(error){banner(error.message,'error')}finally{select.disabled=false}})})}
function renderTeams(){document.querySelector('#teams-list').innerHTML=state.teams.map(item=>`<article class="record-card"><div><span class="tag gold">${escapeHtml(item.division)}</span><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.venue_name||'Venue not assigned')} · Captain: ${escapeHtml(item.captain_name||'Not assigned')}</p></div><button data-delete="teams" data-id="${item.id}">Remove</button></article>`).join('')||'<div class="draw-empty">No teams have been added.</div>'}
function renderVenues(){document.querySelector('#venues-list').innerHTML=state.venues.map(item=>`<article class="record-card"><div><span class="tag gold">${escapeHtml(item.town)}</span><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.address||'Address not added')} · ${Number(item.board_count||1)} match board${Number(item.board_count||1)===1?'':'s'} · Contact: ${escapeHtml(item.contact_name||'Not assigned')}</p></div><button data-delete="venues" data-id="${item.id}">Remove</button></article>`).join('')||'<div class="draw-empty">Add venues before assigning teams.</div>'}
function renderPlayers(){document.querySelector('#players-body').innerHTML=state.players.map(item=>`<tr><td><strong>${escapeHtml(item.name)}</strong></td><td>${escapeHtml(item.team_name||'Unassigned')}</td><td><span class="status Approved">${escapeHtml(item.registration_status)}</span></td><td>${item.appearances}</td><td>${item.wins}</td><td>${item.highest_checkout}</td><td><button data-delete="players" data-id="${item.id}">Remove</button></td></tr>`).join('');document.querySelector('#stats-body').innerHTML=[...state.players].sort((a,b)=>b.one_eighties-a.one_eighties||b.highest_checkout-a.highest_checkout).map(item=>`<tr><td><strong>${escapeHtml(item.name)}</strong></td><td>${escapeHtml(item.team_name||'Unassigned')}</td><td>${item.appearances}</td><td>${item.wins}</td><td>${item.one_eighties}</td><td>${item.highest_checkout}</td></tr>`).join('')}
function renderFixtures(){document.querySelector('#fixtures-list').innerHTML=state.fixtures.map(item=>`<article class="record-card"><div><span class="tag">${fmtDate(item.starts_at)} · ${new Date(item.starts_at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</span><h3>${escapeHtml(item.home_team)} vs ${escapeHtml(item.away_team)}</h3><p>${escapeHtml(item.venue_name||'Venue to be confirmed')} · ${escapeHtml(item.status)}</p></div><button data-delete="fixtures" data-id="${item.id}">Remove</button></article>`).join('')||'<div class="draw-empty">No fixtures have been scheduled.</div>'}
function renderResults(){document.querySelector('#results-list').innerHTML=state.results.map(item=>`<article class="record-card"><div><span class="tag gold">${item.published?'Published':'Draft'} · ${fmtDate(item.starts_at)}</span><h3>${escapeHtml(item.home_team)} ${item.home_score} — ${item.away_score} ${escapeHtml(item.away_team)}</h3><p>Entered by ${escapeHtml(item.entered_by)}</p></div><button data-delete="results" data-id="${item.id}">Remove</button></article>`).join('')||'<div class="draw-empty">No results have been entered.</div>'}
function bindDeletes(){document.querySelectorAll('[data-delete]').forEach(button=>button.addEventListener('click',async()=>{const archived=['teams','venues','players'].includes(button.dataset.delete),message=archived?'Remove this record from active league lists? Historical fixtures and results will be preserved.':'Permanently remove this record?';if(!confirm(message))return;button.disabled=true;try{await api(`admin/${button.dataset.delete}/${button.dataset.id}`,{method:'DELETE'});await loadData();banner(archived?'Record removed from active league lists.':'Record permanently removed.')}catch(error){banner(error.message,'error')}finally{button.disabled=false}}))}
function renderOverview(){const scheduled=state.fixtures.filter(x=>x.status==='scheduled'&&new Date(x.starts_at)>=new Date()).sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at)),next=scheduled[0],divisions=new Set(state.teams.map(x=>x.division).filter(Boolean));document.querySelector('#metric-divisions').textContent=divisions.size?`Across ${divisions.size} division${divisions.size===1?'':'s'}`:'No divisions yet';document.querySelector('#metric-scheduled').textContent=`${scheduled.length} still scheduled`;if(!next)return;const key=next.starts_at.slice(0,10),night=scheduled.filter(x=>x.starts_at.slice(0,10)===key);document.querySelector('#overview-next-date').textContent=new Date(next.starts_at).toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'});document.querySelector('#overview-next-fixtures').innerHTML=night.slice(0,4).map(item=>`<p><span>${escapeHtml(item.home_team)}</span><b>${new Date(item.starts_at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</b><span>${escapeHtml(item.away_team)}</span></p>`).join('')}
function render(){document.querySelector('#application-badge').textContent=state.applications.filter(item=>item.status==='New').length;document.querySelector('#metric-attention').textContent=state.applications.filter(item=>item.status==='New').length;document.querySelector('#metric-teams').textContent=state.teams.length;document.querySelector('#metric-players').textContent=state.players.length;document.querySelector('#metric-fixtures').textContent=state.results.length;document.querySelector('#stat-180s').textContent=state.players.reduce((total,item)=>total+Number(item.one_eighties||0),0);document.querySelector('#stat-checkout').textContent=Math.max(...state.players.map(item=>Number(item.highest_checkout||0)),0);document.querySelector('#stat-matches').textContent=state.results.length;document.querySelector('.user i').textContent=(state.user?.display_name||state.user?.email||'U').slice(0,2).toUpperCase();document.querySelector('.user span').innerHTML=`${escapeHtml(state.user?.display_name||state.user?.email||'Administrator')}<small>${escapeHtml((state.user?.role||'').replace('_',' '))}</small>`;renderApplications();renderTeams();renderVenues();renderPlayers();renderFixtures();renderResults();renderOverview();bindDeletes()}
async function loadData(){const data=await api('admin/bootstrap');Object.assign(state,data);render()}
document.querySelector('#application-search').addEventListener('input',renderApplications);document.querySelector('#application-filter').addEventListener('change',renderApplications);

const dialog=document.querySelector('#record-dialog'),fields=document.querySelector('#dialog-fields');let currentType='teams';
const input=(name,label,type='text',value='')=>`<label>${label}<input name="${name}" type="${type}" value="${value}" ${name==='division'?'list="division-options"':''} required>${name==='division'?'<datalist id="division-options"><option value="Premier Division"><option value="Division One"><option value="Division Two"><option value="Division Three"><option value="Division Four"></datalist>':''}</label>`;
const select=(name,label,items,valueKey='id',labelKey='name')=>`<label>${label}<select name="${name}" required><option value="">Select…</option>${items.map(item=>`<option value="${item[valueKey]}">${escapeHtml(item[labelKey])}</option>`).join('')}</select></label>`;
function formFor(type){if(type==='venues')return input('name','Venue name')+input('town','Town')+input('address','Address')+input('contact_name','Contact name')+input('contact_email','Contact email','email');if(type==='teams')return input('name','Team name')+input('division','Division')+select('venue_id','Home venue',state.venues)+input('captain_name','Captain name')+input('captain_email','Captain email','email');if(type==='players')return input('name','Player name')+input('email','Email','email')+select('team_id','Team',state.teams)+input('appearances','Appearances','number','0')+input('wins','Wins','number','0')+input('one_eighties','180s','number','0')+input('highest_checkout','Highest checkout','number','0');if(type==='fixtures')return select('home_team_id','Home team',state.teams)+select('away_team_id','Away team',state.teams)+select('venue_id','Venue',state.venues)+input('starts_at','Date and time','datetime-local');if(type==='generate-fixtures')return '<label>Division<select name="division" required><option>Premier Division</option><option>Division One</option><option>Division Two</option><option>Division Three</option><option>Division Four</option></select></label>'+input('start_date','First match night','date')+input('start_time','Start time','time','20:00')+'<label>Schedule<select name="home_and_away"><option value="true">Home and away</option><option value="false">Play each team once</option></select></label>';if(type==='results')return select('fixture_id','Fixture',state.fixtures.map(item=>({...item,label:`${item.home_team} v ${item.away_team} · ${fmtDate(item.starts_at)}`})),'id','label')+input('home_score','Home score','number')+input('away_score','Away score','number')+'<label>Publish immediately<select name="published"><option value="false">No — save draft</option><option value="true">Yes — publish</option></select></label>';if(type==='stats')return select('player_id','Player',state.players)+input('appearances','Appearances','number')+input('wins','Wins','number')+input('one_eighties','180s','number')+input('highest_checkout','Highest checkout','number');return ''}
document.querySelectorAll('[data-open]').forEach(button=>button.addEventListener('click',()=>{const mapping={venue:'venues',team:'teams',player:'players',fixture:'fixtures',generator:'generate-fixtures',result:'results',stat:'stats','quick-action':'teams'};currentType=mapping[button.dataset.open]||'teams';document.querySelector('#dialog-title').textContent=currentType==='generate-fixtures'?'Generate division season':`Add ${currentType.replace(/s$/,'')}`;fields.innerHTML=formFor(currentType);dialog.showModal()}));
document.querySelector('#record-form').addEventListener('submit',async event=>{if(event.submitter?.value==='cancel')return;event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));if(values.published)values.published=values.published==='true';if(values.home_and_away)values.home_and_away=values.home_and_away==='true';try{let result;if(currentType==='stats'){result=await api(`admin/players/${values.player_id}`,{method:'PATCH',body:JSON.stringify(values)})}else{result=await api(`admin/${currentType}`,{method:'POST',body:JSON.stringify(values)})}dialog.close();await loadData();banner(currentType==='generate-fixtures'?`${result.fixtures} fixtures generated across ${result.rounds} match weeks.`:'Record saved to the shared league database.')}catch(error){banner(error.message,'error')}});
loadData().then(()=>banner('Connected. Changes are shared and protected.')).catch(error=>{banner(error.message==='Authentication required'?'Sign in through the protected League Office address to continue.':error.message,'error');document.querySelectorAll('.primary').forEach(button=>button.disabled=true)});
