document.body.insertAdjacentHTML('beforeend',`<dialog id="application-details-dialog" class="application-details-dialog"><form method="dialog"><header><div><span id="application-details-type">Application</span><h2 id="application-details-name">Details</h2></div><button value="cancel" aria-label="Close">×</button></header><div id="application-details-content"></div><footer><button value="cancel">Close</button><button type="button" class="primary" id="application-details-email">Email applicant</button></footer></form></dialog>`);
document.head.insertAdjacentHTML('beforeend','<style>.application-details-dialog{width:min(760px,94vw);max-height:88vh;border:0;padding:0}.application-details-dialog::backdrop{background:rgba(0,0,0,.55)}.application-details-dialog form{padding:0}.application-details-dialog header{display:flex;justify-content:space-between;padding:22px 25px;border-bottom:1px solid var(--line)}.application-details-dialog header span{font-size:10px;text-transform:uppercase;color:var(--gold);letter-spacing:.1em}.application-details-dialog h2{margin:3px 0}.application-details-dialog header button{border:0;background:none;font-size:24px}.application-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px;padding:22px 25px}.application-detail-grid article{padding:13px;background:#f4f6f8}.application-detail-grid span{display:block;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.08em}.application-detail-grid strong{display:block;margin-top:4px}.application-detail-wide{grid-column:1/-1}.application-player-details{margin:0;padding-left:20px}.application-player-details li{margin:5px 0}.application-details-dialog footer{display:flex;justify-content:flex-end;gap:9px;padding:17px 25px;border-top:1px solid var(--line)}@media(max-width:560px){.application-detail-grid{grid-template-columns:1fr}.application-detail-wide{grid-column:auto}}</style>');
const applicationDetailSafe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));let detailedApplication=null;
function addApplicationDetailButtons(){document.querySelectorAll('#applications-body .status-change').forEach(select=>{const cell=select.closest('td');if(cell.querySelector('[data-view-application]'))return;const button=document.createElement('button');button.type='button';button.dataset.viewApplication=select.dataset.id;button.textContent='Details';cell.prepend(button,document.createTextNode(' '))})}
const renderApplicationsBeforeDetails=renderApplications;renderApplications=function(){renderApplicationsBeforeDetails();addApplicationDetailButtons()};
function showApplicationDetails(item){detailedApplication=item;document.querySelector('#application-details-type').textContent=`${item.interest_type} application · ${item.status}`;document.querySelector('#application-details-name').textContent=item.name;const players=item.players||[],fields=[['Email',item.email],['Town',item.town],['Received',fmtDate(item.created_at)],['Status',item.status]];if(item.team_name)fields.push(['Team name',item.team_name]);if(item.venue_name)fields.push(['Home venue',item.venue_name]);if(item.venue_address)fields.push(['Venue address',item.venue_address]);if(item.venue_board_count)fields.push(['Match boards',item.venue_board_count]);document.querySelector('#application-details-content').innerHTML=`<div class="application-detail-grid">${fields.map(([label,value])=>`<article><span>${applicationDetailSafe(label)}</span><strong>${applicationDetailSafe(value||'Not supplied')}</strong></article>`).join('')}<article class="application-detail-wide"><span>Applicant message</span><strong>${applicationDetailSafe(item.message||'No message supplied')}</strong></article>${players.length?`<article class="application-detail-wide"><span>Submitted players (${players.length})</span><ol class="application-player-details">${players.map(player=>`<li><strong>${applicationDetailSafe(player.player_name)}</strong>${player.player_email?` · ${applicationDetailSafe(player.player_email)}`:''}</li>`).join('')}</ol></article>`:''}${item.converted_resource?`<article class="application-detail-wide"><span>League record</span><strong>Added to ${applicationDetailSafe(item.converted_resource)} · record ${applicationDetailSafe(item.converted_id)}</strong></article>`:''}</div>`;document.querySelector('#application-details-dialog').showModal()}
document.addEventListener('click',event=>{const button=event.target.closest('[data-view-application]');if(!button)return;const item=state.applications.find(application=>String(application.id)===button.dataset.viewApplication);if(item)showApplicationDetails(item)});
document.querySelector('#application-details-email')?.addEventListener('click',()=>{if(!detailedApplication)return;document.querySelector('#application-details-dialog').close();document.querySelector(`[data-email-application="${detailedApplication.id}"]`)?.click()});
addApplicationDetailButtons();
