const safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),date=value=>value?new Date(String(value).slice(0,10)+'T12:00').toLocaleDateString('en-GB'):'—',section=(title,items)=>`<section class="section"><h2>${safe(title)} <small>(${items.length})</small></h2>${items.length?items.join(''):'<p class="empty">Nothing requiring attention.</p>'}</section>`;document.querySelector('#pack-date').textContent=new Date().toLocaleDateString('en-GB');
async function get(path){const response=await fetch(`/api/admin/${path}`,{credentials:'same-origin'}),data=await response.json();if(!response.ok)throw new Error(data.error||`Unable to load ${path}`);return data}
async function loadPack(){const [bootstrap,agenda,actions,correspondence,cases,suspensions,meetings,trophies]=await Promise.all([get('bootstrap'),get('meeting-agenda'),get('committee-actions'),get('correspondence'),get('disciplinary-cases'),get('player-suspensions'),get('committee-meetings'),get('trophies')]);document.querySelector('#pack-season').textContent=bootstrap.settings?.current_season||'Current season';const today=new Date().toISOString().slice(0,10),blocks=[];
blocks.push(section('Meeting agenda',agenda.items.filter(x=>x.status!=='Discussed').map(x=>`<article class="item"><span class="tag">${safe(x.priority)} · ${safe(x.status)}</span><h3>${safe(x.title)}</h3><p>Meeting ${date(x.meeting_date)} · Submitted by ${safe(x.submitted_by||'Committee')}</p>${x.notes?`<p>${safe(x.notes)}</p>`:''}</article>`)));
blocks.push(section('Outstanding committee actions',actions.actions.filter(x=>x.status!=='Completed').map(x=>`<article class="item"><span class="tag">${safe(x.status)}</span><h3>${safe(x.action_text)}</h3><p>Owner: ${safe(x.owner_name||'Unassigned')} · Due: ${date(x.due_date)}</p>${x.completion_note?`<p>${safe(x.completion_note)}</p>`:''}</article>`)));
blocks.push(section('Correspondence requiring attention',correspondence.items.filter(x=>x.status!=='Complete').map(x=>`<article class="item"><span class="tag">${safe(x.status)}</span><h3>${safe(x.subject)}</h3><p>${safe(x.direction)} · ${safe(x.contact_name)} · Follow up: ${date(x.follow_up_due)}</p>${x.summary?`<p>${safe(x.summary)}</p>`:''}</article>`)));
blocks.push(section('Open disciplinary cases',cases.cases.filter(x=>x.status!=='Resolved').map(x=>`<article class="item"><span class="tag">${safe(x.status)}</span><h3>${safe(x.subject)}</h3><p>Reported ${date(x.reported_at)} · ${safe(x.team_name||'General matter')}</p><p>${safe(x.summary)}</p></article>`)));
blocks.push(section('Active player suspensions',suspensions.suspensions.filter(x=>x.starts_on<=today&&(!x.ends_on||x.ends_on>=today)).map(x=>`<article class="item"><h3>${safe(x.player_name)}</h3><p>${safe(x.team_name||'Unassigned')} · ${date(x.starts_on)} to ${x.ends_on?date(x.ends_on):'until further notice'}</p><p>${safe(x.reason)}</p></article>`)));
blocks.push(section('Draft minutes awaiting approval',meetings.meetings.filter(x=>x.status==='Draft').map(x=>`<article class="item"><h3>${safe(x.meeting_type)} — ${date(x.meeting_date)}</h3><p>${safe(x.location_text||'Location not recorded')}</p></article>`)));
blocks.push(section('Trophies awaiting return',trophies.trophies.filter(x=>!x.returned).map(x=>`<article class="item"><h3>${safe(x.trophy_name)}</h3><p>${safe(x.competition_name)} · Holder: ${safe(x.holder_name||'Not recorded')} · Due: ${date(x.return_due)}</p><p>Engraving: ${x.engraved?'complete':'required'}</p></article>`)));
document.querySelector('#pack-content').innerHTML=blocks.join('')}
loadPack().catch(error=>{document.querySelector('#pack-content').innerHTML=`<p class="private">${safe(error.message)}</p><p>Open this page from the protected League Office after all migrations have been run.</p>`});
