document.head.insertAdjacentHTML('beforeend','<style>.action-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-bottom:15px}.action-form label{display:grid;gap:5px}.action-form input,.action-form textarea,.action-card select,.action-card textarea{padding:10px;border:1px solid var(--line)}.action-wide{grid-column:1/-1}.action-card{align-items:flex-start}.action-controls{width:min(380px,100%)}.action-controls select,.action-controls textarea{display:block;width:100%;margin-bottom:8px}.action-controls textarea{min-height:65px}.action-buttons{display:flex;justify-content:flex-end;gap:8px}.action-overdue{border-left:4px solid #b42318}@media(max-width:750px){.action-form{grid-template-columns:1fr}.action-wide{grid-column:auto}.action-card{display:block}.action-controls{margin-top:12px}}</style>');
const actionForm=document.querySelector('#action-form'),actionList=document.querySelector('#action-list'),actionFilter=document.querySelector('#action-filter'),actionBadge=document.querySelector('#actions-badge'),actionSafe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function actionRequest(path,options={}){const response=await fetch(`/api/admin/${path}`,{credentials:'same-origin',...options,headers:{'content-type':'application/json',...(options.headers||{})}}),data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data}
let committeeActions=[];
function renderActions(){const filter=actionFilter?.value||'active',shown=committeeActions.filter(item=>filter==='all'||(filter==='active'?item.status!=='Completed':item.status===filter)),today=new Date().toISOString().slice(0,10);if(actionBadge)actionBadge.textContent=committeeActions.filter(item=>item.status!=='Completed').length;actionList.innerHTML=shown.length?shown.map(item=>`<article class="record-card action-card ${item.due_date&&item.due_date<today&&item.status!=='Completed'?'action-overdue':''}"><div><span class="tag ${item.status==='Open'?'danger':item.status==='Completed'?'':'gold'}">${actionSafe(item.status)}</span><h3>${actionSafe(item.action_text)}</h3><p>Meeting ${new Date(item.meeting_date+'T12:00').toLocaleDateString('en-GB')} · Owner: ${actionSafe(item.owner_name||'Unassigned')}${item.due_date?` · Due ${new Date(item.due_date+'T12:00').toLocaleDateString('en-GB')}`:''}</p></div><div class="action-controls"><select data-action-status="${item.id}"><option>Open</option><option>In progress</option><option>Completed</option></select><textarea data-action-note="${item.id}" placeholder="Progress or completion note">${actionSafe(item.completion_note||'')}</textarea><div class="action-buttons"><button data-delete-action="${item.id}">Remove</button><button class="primary" data-save-action="${item.id}">Save</button></div></div></article>`).join(''):'<div class="empty"><strong>No matching committee actions</strong><span>New meeting actions will appear here.</span></div>';shown.forEach(item=>{const select=document.querySelector(`[data-action-status="${item.id}"]`);if(select)select.value=item.status})}
async function loadActions(){const [bootstrap,data]=await Promise.all([actionRequest('bootstrap'),actionRequest('committee-actions')]);if(bootstrap.user?.role!=='administrator'){document.querySelector('[data-view="actions"]')?.remove();document.querySelector('#actions-view')?.remove();return}committeeActions=data.actions;renderActions()}
actionForm?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;try{await actionRequest('committee-actions',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();form.elements.meeting_date.value=new Date().toISOString().slice(0,10);await loadActions()}catch(error){alert(error.message)}});
actionList?.addEventListener('click',async event=>{const save=event.target.closest('[data-save-action]'),remove=event.target.closest('[data-delete-action]');try{if(save){const id=save.dataset.saveAction;await actionRequest(`committee-actions/${id}`,{method:'PATCH',body:JSON.stringify({status:document.querySelector(`[data-action-status="${id}"]`).value,completion_note:document.querySelector(`[data-action-note="${id}"]`).value})});await loadActions()}if(remove&&confirm('Remove this committee action?')){await actionRequest(`committee-actions/${remove.dataset.deleteAction}`,{method:'DELETE'});await loadActions()}}catch(error){alert(error.message)}});
actionFilter?.addEventListener('change',renderActions);document.querySelector('#refresh-actions')?.addEventListener('click',loadActions);if(actionForm)actionForm.elements.meeting_date.value=new Date().toISOString().slice(0,10);loadActions().catch(error=>{if(actionList)actionList.innerHTML=`<div class="empty"><strong>${actionSafe(error.message)}</strong></div>`});
