const compSafe=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cupForm=document.querySelector('#cup-generator');let competitionState={cups:[],events:[],teams:[],fixtures:[]};
async function compApi(path,options={}){const response=await fetch(`/api/${path}`,{headers:{'content-type':'application/json'},...options});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to complete request');return data}
function cupReadiness(){const division=cupForm.elements.division.value,cups=competitionState.cups.filter(item=>item.division===division),panel=document.querySelector('#cup-readiness'),button=cupForm.querySelector('button[type="submit"]');if(!cups.length){const teams=competitionState.teams.filter(team=>team.division===division&&Number(team.active)!==0).length;button.disabled=teams<2;panel.className=`cup-readiness ${teams<2?'blocked':'ready'}`;panel.innerHTML=teams<2?`<strong>Not ready</strong><span>Add at least two active teams to ${compSafe(division)}.</span>`:`<strong>First round ready</strong><span>${teams} teams will enter the draw. Choose the match date, then generate it.</span>`;return}const latest=Math.max(...cups.map(item=>Number(item.round_number))),ties=cups.filter(item=>Number(item.round_number)===latest),incomplete=ties.filter(item=>!item.winner_team_id),final=ties.length===1;button.disabled=Boolean(incomplete.length)||final;if(final&&!incomplete.length){panel.className='cup-readiness complete';panel.innerHTML=`<strong>Cup completed</strong><span>${compSafe(ties[0].winner_team)} won the ${compSafe(division)} Cup.</span>`}else if(incomplete.length){panel.className='cup-readiness blocked';panel.innerHTML=`<strong>${incomplete.length} result${incomplete.length===1?'':'s'} still required</strong><span>Complete every ${compSafe(ties[0].round_name)} tie before drawing the next round.</span>`}else{panel.className='cup-readiness ready';panel.innerHTML=`<strong>Next round ready</strong><span>All ${compSafe(ties[0].round_name)} winners will be carried into the next draw automatically.</span>`}}
function suggestCupDate(){const division=cupForm.elements.division.value,dates=competitionState.fixtures.filter(item=>item.competition===`${division} Cup`).map(item=>new Date(item.starts_at)).filter(date=>!Number.isNaN(date.valueOf()));if(!dates.length)return;const next=new Date(Math.max(...dates.map(date=>date.valueOf())));next.setDate(next.getDate()+7);const local=new Date(next.getTime()-next.getTimezoneOffset()*60000).toISOString().slice(0,16);if(!cupForm.elements.starts_at.value)cupForm.elements.starts_at.value=local}
function renderCompetitions(){const data=competitionState;document.querySelector('#cups-list').innerHTML=data.cups.length?data.cups.map(x=>`<article class="record-card"><div><span class="tag gold">${compSafe(x.division)} · ${compSafe(x.round_name)}</span><h3>${compSafe(x.home_team||x.winner_team)} ${x.away_team?'v '+compSafe(x.away_team):'— bye'}</h3><p>${compSafe(x.status)}${x.winner_team?' · Winner: '+compSafe(x.winner_team):''}</p></div><button class="danger" data-cup-delete="${x.id}">Remove cup game</button></article>`).join(''):'<div class="draw-empty">Generate the first round after teams have been added.</div>';document.querySelector('#events-list').innerHTML=data.events.length?data.events.map(x=>`<article class="record-card"><div><span class="tag">${compSafe(x.event_type.replaceAll('_',' '))}</span><h3>${compSafe(x.title)}</h3><p>${new Date(x.starts_at).toLocaleString('en-GB')} · ${compSafe(x.venue_name||x.location_text||'Location TBC')}</p></div><button data-event-delete="${x.id}">Remove</button></article>`).join(''):'<div class="draw-empty">No additional season events yet.</div>';document.querySelectorAll('[data-cup-delete]').forEach(b=>b.onclick=async()=>{if(confirm('Remove this cup game? Its fixture and any recorded result will also be removed.')){try{await compApi(`admin/cup-ties/${b.dataset.cupDelete}`,{method:'DELETE'});await loadCompetitions()}catch(error){alert(error.message)}}});document.querySelectorAll('[data-event-delete]').forEach(b=>b.onclick=async()=>{if(confirm('Remove this calendar event?')){await compApi(`admin/calendar-events/${b.dataset.eventDelete}`,{method:'DELETE'});loadCompetitions()}});cupReadiness();suggestCupDate()}
async function loadCompetitions(){competitionState=await compApi('admin/bootstrap');renderCompetitions()}
cupForm.elements.division.addEventListener('change',()=>{cupForm.elements.starts_at.value='';cupReadiness();suggestCupDate()});
cupForm.addEventListener('submit',async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button[type="submit"]');button.disabled=true;try{const result=await compApi('admin/generate-cup',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});alert(`${result.roundName} generated with ${result.ties} ties.`);await loadCompetitions()}catch(error){alert(error.message);cupReadiness()}});
document.querySelector('#event-form').addEventListener('submit',async e=>{e.preventDefault();try{await compApi('admin/calendar-events',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});e.currentTarget.reset();loadCompetitions()}catch(error){alert(error.message)}});
loadCompetitions();
