document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="fixture-status.css?v=20260904-1">');
let fixtureStatusData=null,rescheduleFixture=null;
const statusSafe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
document.body.insertAdjacentHTML('beforeend','<dialog id="reschedule-dialog"><form id="reschedule-form"><header><div><span>Postponed fixture</span><h2>Choose a new date</h2></div><button type="button" data-close-reschedule aria-label="Close">×</button></header><div class="reschedule-fields"><p id="reschedule-match"></p><label>Reserved catch-up night<select id="catch-up-date"><option value="">Choose a catch-up night</option></select></label><label>Or another date and time<input id="custom-fixture-date" type="datetime-local"></label><small>Selecting a catch-up night fills the new date automatically. You can still change it above.</small></div><footer><button type="button" data-close-reschedule>Cancel</button><button class="primary" type="submit">Reschedule fixture</button></footer></form></dialog>');
const rescheduleDialog=document.querySelector('#reschedule-dialog'),rescheduleForm=document.querySelector('#reschedule-form'),catchUpSelect=document.querySelector('#catch-up-date'),customDate=document.querySelector('#custom-fixture-date');
document.querySelectorAll('[data-close-reschedule]').forEach(button=>button.onclick=()=>rescheduleDialog.close());catchUpSelect.addEventListener('change',()=>{if(catchUpSelect.value)customDate.value=catchUpSelect.value.slice(0,16)});
function openReschedule(fixture){rescheduleFixture=fixture;const catchUps=fixtureStatusData.events.filter(event=>/catch-up/i.test(event.title));document.querySelector('#reschedule-match').innerHTML=`<strong>${statusSafe(fixture.home_team)} v ${statusSafe(fixture.away_team)}</strong><br>Originally ${new Date(fixture.starts_at).toLocaleString('en-GB')}`;catchUpSelect.innerHTML='<option value="">Choose a catch-up night</option>'+catchUps.map(event=>`<option value="${statusSafe(event.starts_at)}">${statusSafe(event.title)} — ${new Date(event.starts_at).toLocaleString('en-GB')}</option>`).join('');customDate.value='';rescheduleDialog.showModal()}
async function updateFixture(fixture,status,startsAt=fixture.starts_at,reason=''){const response=await fetch(`/api/admin/fixtures/${fixture.id}`,{method:'PUT',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({home_team_id:fixture.home_team_id,away_team_id:fixture.away_team_id,venue_id:fixture.venue_id,starts_at:startsAt,status,change_reason:reason})}),result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to update fixture');return result}
rescheduleForm.addEventListener('submit',async event=>{event.preventDefault();if(!rescheduleFixture||!customDate.value)return alert('Choose a catch-up night or enter another date.');const reason=prompt('Reason for the new date','Rearranged after postponement');if(reason===null)return;const button=event.currentTarget.querySelector('[type="submit"]');button.disabled=true;try{await updateFixture(rescheduleFixture,'scheduled',customDate.value,reason);rescheduleDialog.close();alert('Fixture rescheduled and returned to Scheduled. Run Check schedule to confirm there are no clashes.');location.reload()}catch(error){alert(error.message)}finally{button.disabled=false}});
async function addFixtureStatusControls(){if(!fixtureStatusData){const response=await fetch('/api/admin/bootstrap',{credentials:'same-origin'});fixtureStatusData=await response.json();if(!response.ok||fixtureStatusData.user?.role!=='administrator')return}document.querySelectorAll('#fixtures-list .record-card').forEach(card=>{if(card.querySelector('[data-fixture-status]'))return;const remove=card.querySelector('[data-delete="fixtures"]'),fixture=fixtureStatusData.fixtures.find(x=>String(x.id)===remove?.dataset.id);if(!remove||!fixture)return;const actions=document.createElement('div');actions.className='fixture-status-actions';const select=document.createElement('select');select.dataset.fixtureStatus=fixture.id;select.innerHTML='<option value="scheduled">Scheduled</option><option value="postponed">Postponed</option><option value="cancelled">Cancelled</option><option value="completed">Completed</option>';select.value=fixture.status;select.setAttribute('aria-label',`Status for ${fixture.home_team} versus ${fixture.away_team}`);select.addEventListener('change',async()=>{select.disabled=true;try{await updateFixture(fixture,select.value);fixture.status=select.value;alert(`Fixture marked as ${select.value}.`);location.reload()}catch(error){select.value=fixture.status;alert(error.message)}finally{select.disabled=false}});actions.append(select);if(fixture.status==='postponed'){const reschedule=document.createElement('button');reschedule.type='button';reschedule.className='reschedule-button';reschedule.textContent='Reschedule';reschedule.onclick=()=>openReschedule(fixture);actions.append(reschedule)}remove.before(actions)});}
new MutationObserver(addFixtureStatusControls).observe(document.querySelector('#fixtures-list'),{childList:true,subtree:true});addFixtureStatusControls();
