document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="outlook-email.css?v=20260902-1">');
document.body.insertAdjacentHTML('beforeend',`<dialog class="email-dialog" id="email-dialog"><form method="dialog"><header><div><span>Manual Outlook email</span><h2>Email applicant</h2></div><button value="cancel" aria-label="Close">×</button></header><p class="email-hint">This opens a prepared draft in Outlook. You remain in control and press Send yourself.</p><label>Message type<select id="email-template"><option value="received">Application received</option><option value="approved">Application approved and fees due</option><option value="declined">Application declined</option><option value="payment">Payment recorded</option></select></label><label>To<input id="email-to" type="email" readonly></label><label>Subject<input id="email-subject"></label><label>Message<textarea id="email-body"></textarea></label><footer><button value="cancel">Cancel</button><button class="primary" type="button" id="open-outlook">Open in Outlook</button></footer></form></dialog>`);
const leagueEmail='northdorsetdarts@outlook.com';let emailApplication=null;
function feeDetails(item){const players=(item.players||[]).length,team=state.teams.find(row=>String(row.id)===String(item.converted_id)),count=team?Number(team.registered_player_count||0):players,total=team?Number(team.registration_team_fee_pence??2000)+count*Number(team.registration_player_fee_pence??300):2000+count*300,paid=team?Number(team.registration_amount_paid_pence||0):0;return{count,total,paid,balance:Math.max(0,total-paid)}}
function emailCopy(type,item){const first=String(item.name||'').trim().split(/\s+/)[0]||'there',team=item.team_name||item.name,fee=feeDetails(item),money=value=>`£${(value/100).toFixed(2)}`,signature=`Kind regards,\nNorth Dorset Darts League\n${leagueEmail}`;if(type==='approved')return{subject:`${team} — application approved`,body:`Hi ${first},\n\nYour application for ${team} has been approved.\n\nRegistration fee:\n£20.00 team registration\n${fee.count} player${fee.count===1?'':'s'} at £3.00 each\nTotal due: ${money(fee.total)}\n\nPayment can be made by bank transfer or cash. Please reply to this email to arrange payment or confirm how it has been paid.\n\n${signature}`};if(type==='declined')return{subject:'North Dorset Darts League application update',body:`Hi ${first},\n\nThank you for your application to the North Dorset Darts League. Unfortunately, we are unable to approve it at this time.\n\nPlease reply if you would like further information.\n\n${signature}`};if(type==='payment')return{subject:`${team} — registration payment recorded`,body:`Hi ${first},\n\nWe have recorded a registration payment of ${money(fee.paid)} for ${team}.\n\n${fee.balance?`Remaining balance: ${money(fee.balance)}`:'The registration fee is now fully paid.'}\n\n${signature}`};return{subject:'North Dorset Darts League application received',body:`Hi ${first},\n\nThank you for applying to join the North Dorset Darts League. We have received your ${String(item.interest_type||'').toLowerCase()} application${item.team_name?` for ${item.team_name}`:''}.\n\nThe committee will review it and contact you with the next steps. No payment is required until the application has been approved.\n\n${signature}`}}
function fillEmail(){if(!emailApplication)return;const copy=emailCopy(document.querySelector('#email-template').value,emailApplication);document.querySelector('#email-to').value=emailApplication.email||'';document.querySelector('#email-subject').value=copy.subject;document.querySelector('#email-body').value=copy.body}
function addEmailButtons(){document.querySelectorAll('#applications-body .status-change').forEach(select=>{const cell=select.closest('td');if(cell.querySelector('.email-applicant'))return;const button=document.createElement('button');button.type='button';button.className='email-applicant';button.dataset.emailApplication=select.dataset.id;button.textContent='Email';cell.append(button)})}
const renderApplicationsWithoutEmail=renderApplications;renderApplications=function(){renderApplicationsWithoutEmail();addEmailButtons()};
document.querySelector('#application-search').addEventListener('input',addEmailButtons);document.querySelector('#application-filter').addEventListener('change',addEmailButtons);
document.querySelector('#email-template').addEventListener('change',fillEmail);
document.addEventListener('click',event=>{const button=event.target.closest('[data-email-application]');if(!button)return;emailApplication=state.applications.find(item=>String(item.id)===String(button.dataset.emailApplication));if(!emailApplication)return;const suggested=emailApplication.status==='Approved'?'approved':emailApplication.status==='Declined'?'declined':'received';document.querySelector('#email-template').value=suggested;fillEmail();document.querySelector('#email-dialog').showModal()});
document.querySelector('#open-outlook').addEventListener('click',()=>{const to=document.querySelector('#email-to').value,subject=document.querySelector('#email-subject').value,body=document.querySelector('#email-body').value,url=`https://outlook.live.com/mail/0/deeplink/compose?to=${encodeURIComponent(to)}&subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;window.open(url,'_blank','noopener');document.querySelector('#email-dialog').close()});
