const report=document.querySelector('#report'),typeSelect=document.querySelector('#report-type'),divisionSelect=document.querySelector('#division');let league;
const safe=value=>String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
const date=value=>new Date(value).toLocaleDateString('en-GB',{weekday:'short',day:'2-digit',month:'short',year:'numeric'});
function header(title){return `<header class="report-head"><img src="crest.png" alt="League crest"><div><p>North Dorset Darts League</p><h1>${title}</h1><span>${safe(league.settings?.current_season||'Current season')} · produced ${new Date().toLocaleDateString('en-GB')}</span></div></header>`}
function selectedDivisions(){const all=[...new Set(league.teams.map(team=>team.division))].sort();return divisionSelect.value==='all'?all:[divisionSelect.value]}
function tableRows(division){const teams=league.teams.filter(team=>team.division===division),rows=new Map(teams.map(team=>[team.id,{name:team.name,p:0,w:0,l:0,f:0,a:0,pts:0}])),fixtures=new Map(league.fixtures.map(f=>[f.id,f]));league.results.filter(r=>r.published).forEach(result=>{const fixture=fixtures.get(result.fixture_id);if(!fixture||!rows.has(fixture.home_team_id)||!rows.has(fixture.away_team_id)||fixture.competition!=='League')return;const home=rows.get(fixture.home_team_id),away=rows.get(fixture.away_team_id);home.p++;away.p++;home.f+=result.home_score;home.a+=result.away_score;away.f+=result.away_score;away.a+=result.home_score;if(result.home_score>result.away_score){home.w++;away.l++;home.pts+=3}else{away.w++;home.l++;away.pts+=3}});return [...rows.values()].sort((a,b)=>b.pts-a.pts||(b.f-b.a)-(a.f-a)||b.f-a.f||a.name.localeCompare(b.name))}
function renderTables(){const blocks=selectedDivisions().map(division=>{const rows=tableRows(division);return `<section class="division-block"><h2>${safe(division)}</h2>${rows.length?`<table><thead><tr><th>Pos</th><th>Team</th><th>P</th><th>W</th><th>L</th><th>For</th><th>Against</th><th>Diff</th><th>Pts</th></tr></thead><tbody>${rows.map((row,index)=>`<tr><td class="number">${index+1}</td><td>${safe(row.name)}</td><td class="number">${row.p}</td><td class="number">${row.w}</td><td class="number">${row.l}</td><td class="number">${row.f}</td><td class="number">${row.a}</td><td class="number">${row.f-row.a}</td><td class="number"><b>${row.pts}</b></td></tr>`).join('')}</tbody></table>`:'<p class="empty">No teams in this division.</p>'}</section>`}).join('');report.innerHTML=header('Division tables')+blocks+footer()}
function fixturesForDivision(division){return league.fixtures.filter(fixture=>league.teams.find(team=>team.id===fixture.home_team_id)?.division===division)}
function renderFixtures(){const blocks=selectedDivisions().map(division=>{const rows=fixturesForDivision(division).filter(f=>f.status!=='completed').sort((a,b)=>a.starts_at.localeCompare(b.starts_at));return `<section class="division-block"><h2>${safe(division)}</h2>${rows.length?`<table><thead><tr><th>Date</th><th>Competition</th><th>Home</th><th>Away</th><th>Venue</th><th>Status</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${date(row.starts_at)}</td><td>${safe(row.competition)} ${safe(row.round_name||'')}</td><td>${safe(row.home_team)}</td><td>${safe(row.away_team)}</td><td>${safe(row.venue_name||'TBC')}</td><td>${safe(row.status)}</td></tr>`).join('')}</tbody></table>`:'<p class="empty">No upcoming fixtures.</p>'}</section>`}).join('');report.innerHTML=header('Fixture list')+blocks+footer()}
function renderResults(){const fixtures=new Map(league.fixtures.map(f=>[f.id,f])),blocks=selectedDivisions().map(division=>{const rows=league.results.filter(r=>r.published&&league.teams.find(team=>team.id===fixtures.get(r.fixture_id)?.home_team_id)?.division===division).sort((a,b)=>String(b.starts_at).localeCompare(String(a.starts_at)));return `<section class="division-block"><h2>${safe(division)}</h2>${rows.length?`<table><thead><tr><th>Date</th><th>Competition</th><th>Home</th><th>Score</th><th>Away</th></tr></thead><tbody>${rows.map(row=>{const fixture=fixtures.get(row.fixture_id);return `<tr><td>${date(row.starts_at)}</td><td>${safe(fixture?.competition||'League')} ${safe(fixture?.round_name||'')}</td><td>${safe(row.home_team)}</td><td class="number"><b>${row.home_score}–${row.away_score}</b></td><td>${safe(row.away_team)}</td></tr>`}).join('')}</tbody></table>`:'<p class="empty">No published results.</p>'}</section>`}).join('');report.innerHTML=header('Published results')+blocks+footer()}
function footer(){return '<div class="report-foot">Official committee report · North Dorset Darts League</div>'}function render(){({tables:renderTables,fixtures:renderFixtures,results:renderResults}[typeSelect.value]||renderTables)()}
async function start(){try{const response=await fetch('/api/admin/bootstrap',{credentials:'same-origin'}),data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to load report data');league=data;const divisions=[...new Set(data.teams.map(team=>team.division))].sort();divisionSelect.insertAdjacentHTML('beforeend',divisions.map(item=>`<option value="${safe(item)}">${safe(item)}</option>`).join(''));render()}catch(error){report.innerHTML=`<p class="empty">${safe(error.message)}</p>`}}typeSelect.addEventListener('change',render);divisionSelect.addEventListener('change',render);start();
