let scoreData={},existingCard=null;
const sf=document.querySelector('#score-fixture'),homeBox=document.querySelector('#home-four'),awayBox=document.querySelector('#away-four'),gamesBox=document.querySelector('#score-games'),statsBox=document.querySelector('#score-stats');
const opt=items=>items.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');
const playerName=id=>(scoreData.players.find(x=>x.id===Number(id))||{}).name||'Unknown player';

async function scoreLoad(){const response=await fetch('/api/admin/bootstrap'),data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to load fixtures');scoreData=data;const usable=data.fixtures.filter(x=>['scheduled','completed'].includes(x.status));sf.innerHTML='<option value="">Select fixture…</option>'+usable.map(x=>`<option value="${x.id}">${x.home_team} v ${x.away_team} · ${new Date(x.starts_at).toLocaleDateString('en-GB')} (${x.status})</option>`).join('');if(!usable.length)sf.innerHTML='<option value="">No available fixtures</option>'}
function selectedPlayers(box){return [...box.querySelectorAll('select')].map(x=>Number(x.value))}
function setSelections(box,ids){[...box.querySelectorAll('select')].forEach((select,i)=>{if(ids[i])select.value=String(ids[i])})}

function updateGame(row){const inputs=row.querySelectorAll('input[type="number"]'),home=Number(inputs[0].value),away=Number(inputs[1].value),needed=row.dataset.type==='doubles'?2:3,winner=row.querySelector('[data-winner]'),winnerInput=row.querySelector('input[type="hidden"]');row.classList.remove('score-valid','score-invalid');if(inputs[0].value===''||inputs[1].value===''){winner.textContent='Enter legs';winnerInput.value='';return false}const valid=(home===needed&&away>=0&&away<needed)||(away===needed&&home>=0&&home<needed);if(!valid){winner.textContent=row.dataset.type==='doubles'?'Winner must reach 2 legs':'Winner must reach 3 legs';row.classList.add('score-invalid');winnerInput.value='';return false}const teamId=home>away?row.dataset.homeTeam:row.dataset.awayTeam;winnerInput.value=teamId;winner.textContent=home>away?row.dataset.homeName:row.dataset.awayName;row.classList.add('score-valid');return true}

function updateSinglesWins(){document.querySelectorAll('.stat-row').forEach(row=>{row.querySelector('[data-singles-win]').value='0';row.querySelector('[data-singles-label]').textContent='No'});document.querySelectorAll('.game-row[data-type="singles"]').forEach(row=>{const winner=Number(row.querySelector('input[type="hidden"]').value);if(!winner)return;const playerId=winner===Number(row.dataset.homeTeam)?row.dataset.h1:row.dataset.a1,stat=document.querySelector(`.stat-row[data-player="${playerId}"]`);if(stat){stat.querySelector('[data-singles-win]').value='1';stat.querySelector('[data-singles-label]').textContent='Yes'}})}

function fillExisting(){if(!existingCard?.scorecard)return;const singles=existingCard.games.filter(x=>x.game_type==='singles');if(singles.length===4){setSelections(homeBox,singles.map(x=>x.home_player_1_id));setSelections(awayBox,singles.map(x=>x.away_player_1_id))}document.querySelector('#build-games').click();document.querySelectorAll('.game-row').forEach((row,i)=>{const saved=existingCard.games[i];if(!saved)return;const inputs=row.querySelectorAll('input[type="number"]');inputs[0].value=saved.home_legs;inputs[1].value=saved.away_legs;updateGame(row)});existingCard.players.forEach(saved=>{const row=document.querySelector(`.stat-row[data-player="${saved.player_id}"]`);if(!row)return;const inputs=row.querySelectorAll('input:not([type="hidden"])');inputs[0].value=saved.one_eighties;inputs[1].value=saved.highest_checkout;inputs[2].value=saved.highest_shot_in});updateSinglesWins();document.querySelector('#beer-winner').value=existingCard.scorecard.beer_leg_winner_team_id;document.querySelector('#signed-card').checked=Boolean(existingCard.scorecard.signed_scorecard_received);document.querySelector('#score-notes').value=existingCard.scorecard.notes||''}

async function buildScorecard(){const fixture=scoreData.fixtures.find(x=>String(x.id)===sf.value);if(!fixture)return;const response=await fetch(`/api/admin/scorecards/${fixture.id}`);existingCard=response.ok?await response.json():null;const hp=scoreData.players.filter(x=>x.team_id===fixture.home_team_id),ap=scoreData.players.filter(x=>x.team_id===fixture.away_team_id);homeBox.innerHTML=[0,1,2,3].map(i=>`<label>Player ${i+1}<select class="score-select" required>${opt(hp)}</select></label>`).join('');awayBox.innerHTML=[0,1,2,3].map(i=>`<label>Player ${i+1}<select class="score-select" required>${opt(ap)}</select></label>`).join('');gamesBox.innerHTML='<p class="score-help">Choose four different players for each team, then create the match rows.</p><button class="primary" type="button" id="build-games">Create game rows</button>';statsBox.innerHTML='<p class="score-empty">The individual-statistics table will appear after you create the game rows.</p>';document.querySelector('#beer-winner').innerHTML=`<option value="${fixture.home_team_id}">${fixture.home_team}</option><option value="${fixture.away_team_id}">${fixture.away_team}</option>`;
document.querySelector('#build-games').onclick=()=>{const h=selectedPlayers(homeBox),a=selectedPlayers(awayBox);if(new Set(h).size<4||new Set(a).size<4)return alert('Select four different players for each team.');const rows=[['doubles',h[0],h[1],a[0],a[1]],['doubles',h[2],h[3],a[2],a[3]],...h.map((p,i)=>['singles',p,null,a[i],null])];gamesBox.innerHTML=`<p class="score-help">Doubles are best of 3 (first to 2). Singles are best of 5 (first to 3). The winner is calculated automatically.</p><div class="scorecard-scroll"><table class="score-table"><thead><tr><th>Game</th><th>Home player(s)</th><th>Home legs</th><th>Away legs</th><th>Away player(s)</th><th>Winner</th></tr></thead><tbody>${rows.map((r,i)=>{const label=i<2?`Doubles ${i+1}`:`Singles ${i-1}`,homeNames=r[2]?`${playerName(r[1])} & ${playerName(r[2])}`:playerName(r[1]),awayNames=r[4]?`${playerName(r[3])} & ${playerName(r[4])}`:playerName(r[3]);return `<tr class="game-row" data-type="${r[0]}" data-h1="${r[1]}" data-h2="${r[2]||''}" data-a1="${r[3]}" data-a2="${r[4]||''}" data-home-team="${fixture.home_team_id}" data-away-team="${fixture.away_team_id}" data-home-name="${fixture.home_team}" data-away-name="${fixture.away_team}"><td><strong>${label}</strong></td><td>${homeNames}</td><td><input type="number" min="0" max="${r[0]==='doubles'?2:3}" required aria-label="Home legs for ${label}"></td><td><input type="number" min="0" max="${r[0]==='doubles'?2:3}" required aria-label="Away legs for ${label}"></td><td>${awayNames}</td><td><input type="hidden"><strong class="score-winner" data-winner>Enter legs</strong></td></tr>`}).join('')}</tbody></table></div>`;statsBox.innerHTML=`<p class="score-help">Singles wins are calculated from the game results. Only enter each player's 180s, highest checkout and highest shot-in.</p><div class="scorecard-scroll"><table class="score-table"><thead><tr><th>Player</th><th>Team</th><th>Won singles?</th><th>180s</th><th>Highest checkout</th><th>Highest shot-in</th></tr></thead><tbody>${[...h,...a].map(id=>{const p=scoreData.players.find(x=>x.id===id);return `<tr class="stat-row" data-player="${id}"><td><strong>${p.name}</strong></td><td>${p.team_id===fixture.home_team_id?fixture.home_team:fixture.away_team}</td><td><input data-singles-win type="hidden" value="0"><strong data-singles-label>No</strong></td><td><input type="number" min="0" value="0" aria-label="180s for ${p.name}"></td><td><input type="number" min="0" max="170" value="0" aria-label="Highest checkout for ${p.name}"></td><td><input type="number" min="0" max="170" value="0" aria-label="Highest shot-in for ${p.name}"></td></tr>`}).join('')}</tbody></table></div>`;document.querySelectorAll('.game-row input[type="number"]').forEach(input=>input.addEventListener('input',()=>{updateGame(input.closest('.game-row'));updateSinglesWins()}))};
if(existingCard?.scorecard)fillExisting()}

sf.addEventListener('change',buildScorecard);
document.querySelector('#scorecard-form').addEventListener('submit',async e=>{e.preventDefault();const rows=[...document.querySelectorAll('.game-row')];if(rows.length!==6)return alert('Create and complete all six game rows first.');if(!rows.every(updateGame))return alert('Check the leg scores. Doubles must be won 2–0 or 2–1; singles must be won 3–0, 3–1 or 3–2.');updateSinglesWins();const games=rows.map(r=>({game_type:r.dataset.type,home_player_1_id:+r.dataset.h1,home_player_2_id:r.dataset.h2?+r.dataset.h2:null,away_player_1_id:+r.dataset.a1,away_player_2_id:r.dataset.a2?+r.dataset.a2:null,home_legs:+r.querySelectorAll('input[type="number"]')[0].value,away_legs:+r.querySelectorAll('input[type="number"]')[1].value,winner_team_id:+r.querySelector('input[type="hidden"]').value})),players=[...document.querySelectorAll('.stat-row')].map(r=>{const visible=r.querySelectorAll('input:not([type="hidden"])');return{player_id:+r.dataset.player,singles_wins:+r.querySelector('[data-singles-win]').value,one_eighties:+visible[0].value,highest_checkout:+visible[1].value,highest_shot_in:+visible[2].value}}),fixture=scoreData.fixtures.find(x=>String(x.id)===sf.value),homeGames=games.filter(x=>x.winner_team_id===fixture.home_team_id).length,awayGames=6-homeGames,beerId=+document.querySelector('#beer-winner').value,homeScore=homeGames+(beerId===fixture.home_team_id?1:0),awayScore=awayGames+(beerId===fixture.away_team_id?1:0);if(!confirm(`${existingCard?.scorecard?'Update':'Publish'} ${fixture.home_team} ${homeScore}–${awayScore} ${fixture.away_team}?`))return;try{const response=await fetch('/api/admin/scorecards',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fixture_id:+sf.value,games,players,beer_leg_winner_team_id:beerId,signed_scorecard_received:document.querySelector('#signed-card').checked,notes:document.querySelector('#score-notes').value})});const result=await response.json();if(!response.ok)throw new Error(result.error);alert(`Result published: ${result.home_score}–${result.away_score}`);location.reload()}catch(error){alert(error.message)}});
scoreLoad();
