const settingsForm=document.querySelector('#settings-form');
function escapeSetting(value){return String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]))}
async function loadSeasonArchives(){const response=await fetch('/api/admin/season-archives',{credentials:'same-origin'}),data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to load season archive');const list=document.querySelector('#season-archive-list');list.innerHTML=data.archives.length?data.archives.map(item=>`<article class="record-card"><div><span class="tag gold">Archived</span><h3>${escapeSetting(item.season_name)}</h3><p>${item.fixture_count} fixtures · ${item.result_count} results · ${item.team_count} teams · saved ${new Date(item.archived_at).toLocaleDateString('en-GB')}</p></div><a href="/api/admin/season-archives/${item.id}" target="_blank">Download snapshot</a></article>`).join(''):'<p>No completed seasons have been archived yet.</p>'}
async function loadSettings(){const response=await fetch('/api/admin/bootstrap',{credentials:'same-origin'}),data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to load settings');settingsForm.current_season.value=data.settings?.current_season||'2026/27';settingsForm.default_match_time.value=data.settings?.default_match_time||'20:00';document.querySelectorAll('[data-season-label]').forEach(item=>item.textContent=settingsForm.current_season.value);await loadSeasonArchives()}
settingsForm.addEventListener('submit',async event=>{event.preventDefault();const response=await fetch('/api/admin/settings',{method:'PUT',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))}),data=await response.json();if(!response.ok)return alert(data.error||'Unable to save settings');document.querySelectorAll('[data-season-label]').forEach(item=>item.textContent=event.currentTarget.current_season.value);alert('Season settings saved.')});
document.querySelector('#archive-season').addEventListener('click',async()=>{const current=settingsForm.current_season.value.trim(),next=document.querySelector('#next-season-name').value.trim();if(!next)return alert('Enter the next season name first.');if(!confirm(`Archive ${current} and change the website to ${next}? This preserves the current records and does not delete them.`))return;const button=document.querySelector('#archive-season');button.disabled=true;try{const response=await fetch('/api/admin/season-archives',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({next_season:next})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to archive season');settingsForm.current_season.value=next;document.querySelectorAll('[data-season-label]').forEach(item=>item.textContent=next);document.querySelector('#next-season-name').value='';await loadSeasonArchives();alert(`${current} has been archived. The current season is now ${next}.`)}catch(error){alert(error.message)}finally{button.disabled=false}});
document.querySelector('#start-new-season').addEventListener('click',async()=>{const season=settingsForm.current_season.value.trim(),confirmation=prompt(`This clears the live competition data for a fresh ${season} season. Your archived season remains safe.\n\nType ${season} to continue:`);if(confirmation!==season)return;const button=document.querySelector('#start-new-season');button.disabled=true;try{const response=await fetch('/api/admin/start-season',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({confirm_season:season})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to prepare the season');alert(`${season} is ready. Teams, players and venues have been kept; competition records are now blank.`);location.hash='overview';location.reload()}catch(error){alert(error.message)}finally{button.disabled=false}});
document.querySelector('[data-view="settings"]').addEventListener('click',()=>loadSettings().catch(error=>alert(error.message)));
document.addEventListener('click',event=>{if(event.target.closest('[data-open="generator"]'))setTimeout(()=>{const field=document.querySelector('#dialog-fields [name="start_time"]');if(field&&settingsForm.default_match_time.value)field.value=settingsForm.default_match_time.value})});
loadSettings().catch(()=>{});
