document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="treasurer-report.css?v=20260902-1">');
document.querySelector('#fees-view .table-panel').insertAdjacentHTML('afterend',`<section class="panel treasurer-panel"><div class="treasurer-head"><div><h2>Treasurer's payment history</h2><p>Dated cash, bank-transfer and correction entries.</p></div><div class="treasurer-actions"><button type="button" id="refresh-payments">Refresh</button><button type="button" class="primary" id="download-payments">Download CSV</button></div></div><div class="table-panel"><table><thead><tr><th>Date</th><th>Team</th><th>Method</th><th>Amount</th><th>Recorded by</th><th>Note</th></tr></thead><tbody id="payment-history-body"></tbody></table><div class="empty" id="payment-history-empty"><strong>No payments recorded</strong><span>Payment entries will appear after an amount is saved above.</span></div></div></section>`);
let paymentHistory=[];
const paymentMethod=value=>value==='bank_transfer'?'Bank transfer':value==='cash'?'Cash':'Correction';
async function loadPaymentHistory(){try{const data=await api('admin/registration-payments');paymentHistory=data.payments||[];renderPaymentHistory()}catch(error){banner(error.message,'error')}}
function renderPaymentHistory(){const body=document.querySelector('#payment-history-body');body.innerHTML=paymentHistory.map(item=>`<tr><td>${new Date(item.received_at).toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}</td><td><strong>${escapeHtml(item.team_name)}</strong></td><td>${paymentMethod(item.payment_method)}</td><td class="${Number(item.amount_pence)<0?'payment-adjustment':'payment-positive'}">${Number(item.amount_pence)<0?'−':''}${pounds(Math.abs(Number(item.amount_pence)))}</td><td>${escapeHtml(item.received_by)}</td><td>${escapeHtml(item.note||'—')}</td></tr>`).join('');document.querySelector('#payment-history-empty').classList.toggle('show',!!paymentHistory.length===false)}
document.querySelector('#refresh-payments').addEventListener('click',loadPaymentHistory);
document.querySelector('#download-payments').addEventListener('click',()=>{const quote=value=>`"${String(value??'').replace(/"/g,'""')}"`,rows=[['Date','Team','Method','Amount GBP','Recorded by','Note'],...paymentHistory.map(item=>[item.received_at,item.team_name,paymentMethod(item.payment_method),(Number(item.amount_pence)/100).toFixed(2),item.received_by,item.note||''])],blob=new Blob([rows.map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`north-dorset-darts-payments-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href)});
document.addEventListener('click',event=>{if(event.target.closest('[data-save-fee]'))setTimeout(loadPaymentHistory,600)});
loadPaymentHistory();
